### ISSUE TITLE
media library not displaying uploaded files

### ISSUE THREAD

**Issue by rrubio** [arrowheadapps/strapi-connector-firestore#47] opened 2021-02-07 14:11 UTC
Hi Guys,

I'm using the following media library - https://www.npmjs.com/package/strapi-provider-upload-google-cloud-storage

Uploading files works and are also available to the public via the bucket URL. But under media library, no images display, however, the page recognizes that there is content available by displaying the page count underneath.

I am running cloudrun and under Cloud firestore, i can see a populated table "upload_file".

![image](https://user-images.githubusercontent.com/4221574/107149002-62549800-69aa-11eb-94bd-24cb5fcb3504.png)

Any help is much appreciated.

**Comment by brettwillis** [comment] 2021-02-07 19:46
Hi @rrubio ,
What is the contents of your upload plugin config file, and the database config file?

Also, when you load that page, are there any error or warning logs in Cloud Logging, or in the browser JavaScript developer console?

**Comment by rrubio** [comment] 2021-02-07 22:47
@brettwillis see config below. When the page loads up there are no errors. 

`module.exports = ({ env }) => {

  // Use Cloud Storage for production environment only
  if (env('NODE_ENV') === 'production') {
    return {
      upload: {
        provider: 'google-cloud-storage',
        providerOptions: {
          bucketName: ;'my-project-id.appspot.com',
          basePath: '',
          publicFiles: true,
          uniform: false,
        },
      },
    };
  }
};
`

Returned data array - 

![image](https://user-images.githubusercontent.com/4221574/107161699-95bb1500-69f2-11eb-9005-c7f9734089da.png)

Returned count - 

![image](https://user-images.githubusercontent.com/4221574/107161709-a79cb800-69f2-11eb-9a09-5ec8143bbaff.png)

**Comment by rrubio** [comment] 2021-02-08 10:59
@brettwillis see db config below:

`module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'firestore',
      settings: {
        // This not required for production
        // But it is required for the Firestore emulator UI otherwise
        // it won't show any data
        projectId: env('npm_package_project_id'),
      },
      options: {
        useEmulator: env('NODE_ENV') !== 'production',
        logQueries: env('NODE_ENV') !== 'production',
      }
    }
  },
});
`

**Comment by rrubio** [comment] 2021-02-09 13:44
@brettwillis thank you! see below:

`  "dependencies": {
    "strapi": "^3.4.4",
    "strapi-admin": "^3.4.4",
    "strapi-connector-firestore": "^3.0.0-alpha.27",
    "strapi-plugin-content-manager": "^3.4.4",
    "strapi-plugin-content-type-builder": "^3.4.4",
    "strapi-plugin-email": "^3.4.4",
    "strapi-plugin-upload": "^3.4.4",
    "strapi-plugin-users-permissions": "^3.4.4",
    "strapi-provider-upload-google-cloud-storage": "^3.1.6",
    "strapi-utils": "^3.4.4"
  },
`

**Comment by brettwillis** [comment] 2021-02-19 03:47
Ok, it looks like the upload plugin is not respecting this connector's nominated timestamp field names. It is applying a sort on `"updated_at"` where as this connector's timestamp field is `"updatedAt"`, so it's having the effect of filtering out every entry.

I need to investigate whether this is a problem with this connector or a regression in Strapi (unlikely I guess). 

The official MongoDB connector also uses `"updatedAt"` instead of `"updated_at"`, and I can't find anything I'm doing differently from the MongoDB connector in the way that the timestamp fields are nominated...

Do you have a setup running MonngoDB? If so, does it also have the same problem?

**Comment by brettwillis** [comment] 2021-02-19 18:33
@rrubio never mind about that last question. MongoDB behaves differently from Firestore such that sorting on a non-existent field doesn't have the effect of filtering.

And I think I've found the bug/regression in Strapi is causing this. It has probably been sleeping without being noticed because the aforementioned MongoDB behaviour masks it.

I'll try to work on a PR for this in Strapi.

**Comment by rrubio** [comment] 2021-02-23 22:47
@brettwillis thank you man! really appreciate it.

**Comment by brettwillis** [comment] 2021-03-01 18:38
@rrubio Strapi v3.5.2 has been released with a fix for this issue. Please update, and it should be resolved.

I'm going to close this issue, but please feel free let me know if there is any further problem.

**Closed** 2021-03-01 18:38 UTC
Labels: bug
